### ISSUE TITLE
SAM deploy idempotency expectation?

### ISSUE THREAD

**Issue by heffergm** [aws/aws-sam-cli#2154]
### Description

Currently, working from the same codebase, running `sam deploy` on one machine and then again on another will trigger a full deployment workflow (function code updates, codedeploy deployment, etc) even though no code has changed.

### Steps to reproduce

On system X, run `sam build && sam deploy`; if there are changes pending, apply them. Re-run so that you confirm an empty changeset.

On system Y, using the same codebase, run `sam build && sam deploy` and a full stack update/changeset is created and deployed, despite no code changes. If applied and re-run, the changeset will again be empty.

Now go back to system X and repeat the process, and again there is a full stack changeset pending.

### Expected result

When there are no code/template (indeed, not any) changes, I would not expect that the origin point of the deploy process would trigger a complete stack update.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

`SAM CLI, version 1.0.0`

In my example above, system X is a local OSX machine, system Y is a Linux GitLab CI runner.

My only inclination is that this has something to do with the local .aws-sam cache.

**Comment by timoschilling** [comment]
Which runtime do you use. I can't confirm you case for ruby for example.

**Comment by heffergm** [comment]
Python3.7

**Comment by heffergm** [comment]
These are moments apart. It's probably worth noting our setup is on the complex end of the spectrum (pre/post deploy hooks, multiple functions, etc). If I went ahead and applied the change locally, the next run on gitlab would result in a full changeset. However if I re-run from gitlab in this case (clean changeset first run) subsequent runs will remain clean. The same holds true for the reverse.

## my local setup
```
Build Succeeded

Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml

Commands you can use next
=========================
[*] Invoke Function: sam local invoke
[*] Deploy: sam deploy --guided

Uploading to ourapp-prod-app/2212e79ccbcb3fbb6ee85a6f767b69e2  7362084 / 7362084.0  (100.00%)
Uploading to ourapp-prod-app/d7440d6438d501a69d79aeee146bec91  536556 / 536556.0  (100.00%)

	Deploying with following values
	===============================
	Stack name                 : ourapp-prod-app
	Region                     : us-east-2
	Confirm changeset          : True
	Deployment s3 bucket       : a-obfuscated-bucket
	Capabilities               : ["CAPABILITY_IAM"]
	Parameter overrides        : {'EnvType': 'prod'}

Initiating deployment
=====================
Uploading to ourapp-prod-app/003e863f19e352e730ef87ce33652632.template  23469 / 23469.0  (100.00%)

Waiting for changeset to be created..

CloudFormation stack changeset
------------------------------------------------------------------------------------------------------------------
Operation                              LogicalResourceId                      ResourceType
------------------------------------------------------------------------------------------------------------------
+ Add                                  OurAppAuthorizerVersionda2760f4e4         AWS::Lambda::Version
+ Add                                  OurAppLambdaDeps59c51e0164                AWS::Lambda::LayerVersion
+ Add                                  ErrorLookupVersionf1f85481ae           AWS::Lambda::Version
* Modify                               ApiGatewayTokenAuthorizerAuthorizerP   AWS::Lambda::Permission
                                       ermission
* Modify                               ApiGateway                             AWS::ApiGateway::RestApi
* Modify                               OurAppAuthorizerAliasLive                 AWS::Lambda::Alias
* Modify                               OurAppAuthorizerLatestVersionErrorMetri   AWS::CloudWatch::Alarm
                                       cGreaterThanZeroAlarm
* Modify                               OurAppAuthorizer                          AWS::Lambda::Function
* Modify                               OurAppUploadBucket                        AWS::S3::Bucket
* Modify                               ErrorLookupAliasLive                   AWS::Lambda::Alias
* Modify                               ErrorLookupLatestVersionErrorMetricG   AWS::CloudWatch::Alarm
                                       reaterThanZeroAlarm
* Modify                               ErrorLookupPostTrafficHook             AWS::Lambda::Function
* Modify                               ErrorLookupPreTrafficHook              AWS::Lambda::Function
* Modify                               ErrorLookup                            AWS::Lambda::Function
* Modify                               UploadData                             AWS::Lambda::Function
- Delete                               OurAppAuthorizerVersion045b8cdb5c         AWS::Lambda::Version
- Delete                               OurAppLambdaDepsf2d3e497c2                AWS::Lambda::LayerVersion
- Delete                               ErrorLookupVersion7afc9a31f8           AWS::Lambda::Version
------------------------------------------------------------------------------------------------------------------

Changeset created successfully. arn:aws:cloudformation:us-east-2:122012841907:changeSet/samcli-deploy1596658485/2ae586ae-dc10-4dd8-aa2a-c8dea763517d


Previewing CloudFormation changeset before deployment
======================================================
Deploy this changeset? [y/N]:
```


## Gitlab runner (docker executor):

```
124 	Deploying with following values
125 	===============================
126 	Stack name                 : ourapp-prod-app
127 	Region                     : us-east-2
128 	Confirm changeset          : False
129 	Deployment s3 bucket       : a-obfuscated-bucket
130 	Capabilities               : ["CAPABILITY_IAM"]
131 	Parameter overrides        : {'EnvType': 'prod'}
132 Initiating deployment
133 =====================
134 Waiting for changeset to be created..
135 No changes to deploy. Stack ourapp-prod-app is up to date
```

**Comment by timoschilling** [comment]
What happens if you deploy multiple times from your Mac?

**Comment by heffergm** [comment]
Same deal: if there's a changeset to apply and I apply it, subsequent runs are clean.

**Comment by mndeveci** [comment]
Hi @timoschilling and @heffergm 

Thanks for comments here. I tried to reproduce the problem by running `sam build -u && sam deploy -g` for the same project to the same AWS account from two different development machines.

For the first deploy everything seen as new and created all the resources.
Second deploy only saw the part as modified (I believe that is related to re-running build command), see the diff from the second deploy command below;
```
CloudFormation stack changeset
---------------------------------------------------------------------------------------------------------------------------------------------------------
Operation                                           LogicalResourceId                                   ResourceType
---------------------------------------------------------------------------------------------------------------------------------------------------------
* Modify                                            HelloMarsFunction                                   AWS::Lambda::Function
* Modify                                            ServerlessRestApi                                   AWS::ApiGateway::RestApi
---------------------------------------------------------------------------------------------------------------------------------------------------------
```

@heffergm can you give more detail for your example, or can you provide an example that we can reproduce?

Thanks,
Mehmet

**Comment by heffergm** [comment]
Thanks for looking into it.

My suspicion is, since this clearly isn't a low level issue, that there's something specific to our configuration that's resulting in this behavior. I'll see if I can put a minimal setup together that reproduces the issue.

**Comment by heffergm** [comment]
So I've got a basic usable example, tgz attached. It's a good representation of the infrastructure elements we're using in our stacks but with all the code removed. Running `build_and_deploy.sh` from different systems produces the results I originally described. 

Just to briefly reiterate:
- run from SystemX: apply changeset if pending
- run from SystemX again: no changes to apply
- copy tgz to SystemY: full changeset will be applied on initial run
- run again from SystemY: no changes pending

[dev-test-sam.tar.gz](https://github.com/awslabs/aws-sam-cli/files/5042083/dev-test-sam.tar.gz)

**Comment by mndeveci** [comment]
Hi @heffergm ,

I was able to re-generate the issue as you mentioned. It is related the way we generate md5 (hashing) of the deployable packages. And apparently, they are different from different operating systems.

Created a PR to address the issue.

**Comment by mndeveci** [comment]
Fixed with https://github.com/awslabs/aws-sam-cli/pull/2163, waiting for next release

**Comment by mndeveci** [comment]
Released with [SAM CLI v1.2.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.2.0)

**Comment by heffergm** [comment]
FYI, this has fixed a majority of what I originally reported (thanks!). 

I do notice, however, that I'm still getting the same sort of thing happening when using layers:

```
CloudFormation stack changeset
------------------------------------------------------------------------------------------------------------------
Operation                              LogicalResourceId                      ResourceType
------------------------------------------------------------------------------------------------------------------
+ Add                                  commons91b80fbd7e                      AWS::Lambda::LayerVersion
* Modify                               ArkUploadBucket                        AWS::S3::Bucket
* Modify                               ErrorLookupPostTrafficHook             AWS::Lambda::Function
* Modify                               ErrorLookup                            AWS::Lambda::Function
* Modify                               ErrorMetadataPostTrafficHook           AWS::Lambda::Function
* Modify                               ErrorMetadata                          AWS::Lambda::Function
* Modify                               UploadData                             AWS::Lambda::Function
- Delete                               commons87a04fe31b                      AWS::Lambda::LayerVersion
------------------------------------------------------------------------------------------------------------------
```

So rather than a full stack changeset being created, we get a minimal changeset created only related to the application of a layer. I'm wondering if there's something similar going on related to the packaging of layer dependencies as related to creating md5sums.

**Comment by mndeveci** [comment]
@heffergm thanks for reporting issue with Layers. Would you able to provide us example project that we can use to re-produce this? I am asking because we weren't able to reproduce original issue with functions in the beginning.

Thanks!

**Comment by heffergm** [comment]
At the moment, I'm unable to do so using my original test case as a template. I'll need to dig into it more at some point...

**Comment by heffergm** [comment]
@mndeveci go ahead and close this, I can't reliably reproduce the layer issue. If I can come up with a working test case I'll open a new ticket and reference this. Thanks for humoring me!

**Comment by mndeveci** [comment]
Sorry to hear that @heffergm, please fell free to re-open this one or create a new issue if you can identify the example for layers.
