### ISSUE TITLE
SAM cli 1.13.2+ Go debugging broken

### ISSUE THREAD

**Issue by hunterwerlla** [aws/aws-sam-cli#2462]
### Description:

Attempting to debug a go lambda with sam cli start-api/invoke makes the lambda code fail to start

### Steps to reproduce:
1. Create a sam app with these parameters using 1.13.2
```
    -----------------------
    Generating application:
    -----------------------
    Name: test113sam
    Runtime: go1.x
    Dependency Manager: mod
    Application Template: hello-world
    Output Directory: .

    Next steps can be found in the README file at ./test113sam/README.md
```
2. `sam build`
3. run `sam local invoke` it works fine:
```
$ sam local invoke
Invoking hello-world (go1.x)
Skip pulling image and use local one: amazon/aws-sam-cli-emulation-image-go1.x:rapid-1.13.2.

Mounting /private/tmp/test113sam/.aws-sam/build/HelloWorldFunction as /var/task:ro,delegated inside runtime container
START RequestId: d1f12116-37df-4127-9b64-36aacdccea8c Version: $LATEST
END RequestId: d1f12116-37df-4127-9b64-36aacdccea8c
REPORT RequestId: d1f12116-37df-4127-9b64-36aacdccea8c	Init Duration: 1.57 ms	Duration: 785.02 ms	Billed Duration: 800 ms	Memory Size: 128 MB	Max Memory Used: 128 MB
{"statusCode":200,"headers":null,"multiValueHeaders":null,"body":"Hello, 72.21.198.67\n"}
```
Now, try invoking with Devle debugger args:
```
sam local invoke --debug-args -delveAPI=2 --debugger-path /Users/werlla/IdeaProjects/go1sam/ --debug-port 59394 --debug
2020-12-07 13:10:50,211 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2020-12-07 13:10:50,418 | local invoke command is called
2020-12-07 13:10:50,427 | No Parameters detected in the template
2020-12-07 13:10:50,454 | 2 resources found in the template
2020-12-07 13:10:50,455 | Found Serverless function with name='HelloWorldFunction' and CodeUri='HelloWorldFunction'
2020-12-07 13:10:50,464 | Found one Lambda function with name 'HelloWorldFunction'
2020-12-07 13:10:50,464 | Invoking hello-world (go1.x)
2020-12-07 13:10:50,464 | Environment variables overrides data is standard format
2020-12-07 13:10:50,464 | Loading AWS credentials from session with profile 'None'
2020-12-07 13:10:51,929 | Resolving code path. Cwd=/private/tmp/test113sam/.aws-sam/build, CodeUri=HelloWorldFunction
2020-12-07 13:10:51,929 | Resolved absolute path to code is /private/tmp/test113sam/.aws-sam/build/HelloWorldFunction
2020-12-07 13:10:51,930 | Code /private/tmp/test113sam/.aws-sam/build/HelloWorldFunction is not a zip/jar file
2020-12-07 13:10:53,185 | Failed to download image with name amazon/aws-sam-cli-emulation-image-go1.x:debug-1.13.2
2020-12-07 13:10:53,185 | Failed to download a new amazon/aws-sam-cli-emulation-image-go1.x:debug-1.13.2 image. Invoking with the already downloaded image.
2020-12-07 13:10:53,186 | Mounting /private/tmp/test113sam/.aws-sam/build/HelloWorldFunction as /var/task:ro,delegated inside runtime container
2020-12-07 13:10:53,859 | Setting up SIGTERM interrupt handler
2020/12/07 21:10:53 Error starting mock server: fork/exec /var/rapid/init: no such file or directory
2020-12-07 13:10:54,710 | No response from invoke container for HelloWorldFunction
2020-12-07 13:10:54,711 | Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam local invoke', 'duration': 4498, 'exitReason': 'success', 'exitCode': 0, 'requestId': 'fd63fac1-9b23-4de9-a4ab-e6b76e979b13', 'installationId': '8e36c82e-d3f0-45b7-9e48-1e6f0ad535a6', 'sessionId': '10201463-def2-41d3-97ea-e2c5b3ee5e6f', 'executionEnvironment': 'CLI', 'pyversion': '3.8.6', 'samcliVersion': '1.13.2'}}]}
2020-12-07 13:10:54,880 | Telemetry response: 200
```

### Observed result:

```
2020/12/07 21:10:53 Error starting mock server: fork/exec /var/rapid/init: no such file or directory
```
And it does not start. 
```
sam local invoke --debug-args "-delveAPI=2" --debugger-path /Users/werlla/IdeaProjects/go1sam/ --debug-port 59394 --debug
```
Quoting debug args results in the same output, and single quoting debug args leads to some more strange output without it running 
```
 sam local invoke --debug-args '-delveAPI=2' --debugger-path /Users/werlla/IdeaProjects/go1sam/ --debug-port 59394 --debug
2020-12-07 13:15:41,148 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2020-12-07 13:15:41,541 | local invoke command is called
2020-12-07 13:15:41,548 | No Parameters detected in the template
2020-12-07 13:15:41,589 | 2 resources found in the template
2020-12-07 13:15:41,589 | Found Serverless function with name='HelloWorldFunction' and CodeUri='HelloWorldFunction'
2020-12-07 13:15:41,608 | Found one Lambda function with name 'HelloWorldFunction'
2020-12-07 13:15:41,608 | Invoking hello-world (go1.x)
2020-12-07 13:15:41,608 | Environment variables overrides data is standard format
2020-12-07 13:15:41,609 | Loading AWS credentials from session with profile 'None'
2020-12-07 13:15:43,363 | Resolving code path. Cwd=/private/tmp/test113sam/.aws-sam/build, CodeUri=HelloWorldFunction
2020-12-07 13:15:43,363 | Resolved absolute path to code is /private/tmp/test113sam/.aws-sam/build/HelloWorldFunction
2020-12-07 13:15:43,363 | Code /private/tmp/test113sam/.aws-sam/build/HelloWorldFunction is not a zip/jar file
2020-12-07 13:15:44,558 | Failed to download image with name amazon/aws-sam-cli-emulation-image-go1.x:debug-1.13.2
2020-12-07 13:15:44,558 | Failed to download a new amazon/aws-sam-cli-emulation-image-go1.x:debug-1.13.2 image. Invoking with the already downloaded image.
2020-12-07 13:15:44,558 | Mounting /private/tmp/test113sam/.aws-sam/build/HelloWorldFunction as /var/task:ro,delegated inside runtime container
2020-12-07 13:15:45,629 | Setting up SIGTERM interrupt handler
2020-12-07 13:15:46,391 | No response from invoke container for HelloWorldFunction
2020-12-07 13:15:46,392 | Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam local invoke', 'duration': 5242, 'exitReason': 'success', 'exitCode': 0, 'requestId': '61ed57b7-4d4d-4081-b4b7-88af18a3ec2f', 'installationId': '8e36c82e-d3f0-45b7-9e48-1e6f0ad535a6', 'sessionId': 'a568cab5-a111-40a0-bfef-a9800ec0a2a4', 'executionEnvironment': 'CLI', 'pyversion': '3.8.6', 'samcliVersion': '1.13.2'}}]}
2020-12-07 13:15:46,521 | Telemetry response: 200
```

### Expected result:

Running with the same arguments starts correctly with sam cli `1.12.0`

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac
2. `sam --version`: SAM CLI, version 1.13.2

**Comment by michael-kleemann** [comment]
I'm also seeing this issue. I've set up the hello-world via sam init and pretty much did the same commands as above.
So that is exactly the usecase which is described in the docs on how to debug with go.

Downgrading to v1.12.0 worked for me(Had to reinstall via pip `pip3 install --user 'aws-sam-cli==1.12.0'`)

**Comment by aahung** [comment]
Some initial findings:

In https://github.com/aws/aws-sam-cli/pull/2425, the file `/local/rapid/init` was changed to `/local/rapid/aws-lambda-rie`, while in “samcli/local/go-bootstrap/aws-lambda-mock.go:96” `rapid/init` is still used.

This can be easily fixed in #2544. However, with #2544, we see a new error:

```
2021/01/20 00:50:48 http: panic serving 127.0.0.1:49540: &{0xc0001c8000 map[] 2021-01-20 00:50:48.4458573 +0000 UTC m=+0.017114501 panic <nil> ReplyStream not available <nil> <nil> }
goroutine 35 [running]:
net/http.(*conn).serve.func1(0xc0002880a0)
	/usr/local/go/src/net/http/server.go:1800 +0x139
panic(0x866640, 0xc0002cc150)
	/usr/local/go/src/runtime/panic.go:975 +0x3e3
github.com/sirupsen/logrus.Entry.log(0xc0001c8000, 0xc0002845a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:259 +0x335
```

(full text: [1611104121.txt](https://github.com/aws/aws-sam-cli/files/5840043/1611104121.txt))

We narrow the cause to the same PR (#2425, commit SHA: 12efe15b682926b006ce2a846d7cc6c71f5f2d74).

* with 12efe1 and 2544 fix, we have this error when running `local invoke` with delve debugger.
* without 12efe1, everything works fine.

### How to reproduce the (new) error?

(See our official guide ["Step-through debugging Lambda functions locally"](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-debugging.html) for full details)
0. check out #2544, which contains the fix of the original error.
1. Install delve ([on macOS](https://github.com/go-delve/delve/blob/master/Documentation/installation/osx/install.md)), assuming it is install to `/Users/xxx/go/bin/dlv`.
2. build the hello world project with `sam build`
3. `sam local invoke`, now it works with or without 12efe1
4. `sam local invoke --debug-args -delveAPI=2 --debugger-path /Users/xxx/go/bin/ --debug-port 59394 --debug`, the error above shows up.

We have a guess: `aws-lambda-mock.go` does not play nicely with the new `aws-lambda-rie`. The error message is not very helpful, we need to isolate what inputs to the lambda container cause this problem by doing some experiments.

**Comment by aahung** [comment]
We found the issue and working on developing a fix. If you need this feature urgently, you can try the workaround #2548.

```sh
git clone git@github.com:aws/aws-sam-cli.git
cd aws-sam-cli
git pull origin pull/2548/head
python3 -m venv .env
source .env/bin/activate
make init 
# then you can use samdev to replace sam for local invoking
samdev local invoke...
```

**Comment by aahung** [comment]
Update: we are working on a fix

**Comment by aahung** [comment]
sam-cli 1.17.0 should fix this bug

**Comment by michael-kleemann** [comment]
I tried with the new version 1.17.0 but i'm still not able to debug with goland.
What surprised me was this in the logs `Ignoring unrecognized arguments: ['-delveAPI=2']`
It tried with `--debug-args "--api-version=2 --log"` as i've seen in your comment but again `Ignoring unrecognized arguments: ['--api-version=2', '--log']`
This might be a different issue but debugging as described in developer guide is still not possible.

**Comment by aahung** [comment]
> I tried with the new version 1.17.0 but i'm still not able to debug with goland.
> What surprised me was this in the logs `Ignoring unrecognized arguments: ['-delveAPI=2']`
> It tried with `--debug-args "--api-version=2 --log"` as i've seen in your comment but again `Ignoring unrecognized arguments: ['--api-version=2', '--log']`
> 
> This might be a different issue but debugging as described in developer guide is still not possible.
> Went back to 1.12.0 and debugging is working again as described.

Thanks for reporting, about `Ignoring unrecognized arguments: ['-delveAPI=2']`, it is a bug in 1.17.0 that only `-delveApi` can be recognized. Can you try again with `-delveApi=2` for now while we work on a fix?

**Comment by michael-kleemann** [comment]
> > I tried with the new version 1.17.0 but i'm still not able to debug with goland.
> > What surprised me was this in the logs `Ignoring unrecognized arguments: ['-delveAPI=2']`
> > It tried with `--debug-args "--api-version=2 --log"` as i've seen in your comment but again `Ignoring unrecognized arguments: ['--api-version=2', '--log']`
> > This might be a different issue but debugging as described in developer guide is still not possible.
> > Went back to 1.12.0 and debugging is working again as described.
> 
> Thanks for reporting, about `Ignoring unrecognized arguments: ['-delveAPI=2']`, it is a bug in 1.17.0 that only `-delveApi` can be recognized. Can you try again with `-delveApi=2` for now while we work on a fix?

That works perfectly me. Thanks a lot.

**Comment by mgrandis** [comment]
Should be fixed in 1.18.1
https://github.com/aws/aws-sam-cli/releases/tag/v1.18.1
