### ISSUE TITLE
Feature request: AWS::LanguageExtensions support

### ISSUE THREAD

**Issue by jdel** [aws/aws-sam-cli#4172]
### Describe your idea/feature/enhancement

I wish SAM CLI would handle the new AWS::LanguageExtensions transform as specified in the documentation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-languageextension-transform.html

Example template:
```yml
AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Conditions:
  IsProd: !Equals [!Ref Environment, prod]

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: !If [IsProd, Retain, Delete]
    UpdateReplacePolicy: !If [IsProd, Retain, Delete]
```

`AWS CLI`, version 2.7.7 succeeds with:
```
❯ aws cloudformation deploy --stack-name test-language-extension --template-file sam/test-template.yml

Waiting for changeset to be created..
Waiting for stack create/update to complete
Successfully created/updated stack - test-language-extension
```

`SAM CLI`, version 1.55.0 fail with:
```
sam deploy --stack-name test-language-extension --template-file sam/test-template.yml
Traceback (most recent call last):
[... redacted stack trace ...]
  File "/usr/local/Cellar/aws-sam-cli/1.55.0/libexec/lib/python3.8/site-packages/samcli/lib/samlib/wrapper.py", line 70, in run_plugins
    raise InvalidSamDocumentException(
samcli.commands.validate.lib.exceptions.InvalidSamDocumentException: [InvalidTemplateException('Every DeletionPolicy member must be a string.')] Every DeletionPolicy member must be a string.
```

### Proposal

Implement the same changes as `aws-cli` and `cfn-lint`

For reference, the releases/announcements from both tools 
  - https://github.com/aws-cloudformation/cfn-lint/compare/v0.62.0..v0.63.0
  - https://github.com/aws/aws-cli/issues/3825#issuecomment-1231608258

Things to consider:
The order of the transforms is important and using multiple transforms is currently broken in `cfn-lint` https://github.com/aws-cloudformation/cfn-lint/issues/2346

### Additional Details

No additional details

**Comment by jfuss** [comment]
@jdel Can you be more specific in what you what the CLI to do? It's not clear what "handle the new AWS::LanguageExtension" means for the CLI.

**Comment by jdel** [comment]
I updated my original post with a link to the documentation. I am not familiar with sam cli code base to suggest where the code should be implemented but I included a diff from `cfn-lint` to show how they did. I haven't found a similar code example with `aws-cli` but it is working as expected with `aws cloudformation deploy`. Maybe you can leverage knowledge and implementation from those 2 projects for `sam-cli`.

Please pay attention at the broken implementation in `cfn-lint` mentioned in the `Things to consider`. I also raised a ticket there explaining that when using more than one transform the implementation is broken.

**Comment by jdel** [comment]
Thanks for the details, I also edited my OP again to provide a simple template to test.

**Comment by mildaniel** [comment]
This issue has now been resolved in version 1.56.1. I will close this issue but please re-open if required.

**Comment by cortexcompiler** [comment]
This does not appear to be fully implemented.  `sam deploy` works fine when using `AWS::LanguageExtensions` and specifying a conditional for `DeletionPolicy`, but `sam validate still fails with:
```
Template provided at '/<path omitted>/template.yaml' was invalid SAM Template.
Error: [InvalidTemplateException('Every DeletionPolicy member must be a string.')] Every DeletionPolicy member must be a string.
```

The template has the following at the top:
```
AWSTemplateFormatVersion: "2010-09-09"
Transform:
- AWS::LanguageExtensions
- AWS::Serverless-2016-10-31
```

**Comment by napso** [comment]
Getting the same error as @cortexcompiler  
was there any update on that?

**Comment by rdallasgray** [comment]
Adding to this, deployment to the Serverless Application Repository doesn't seem to support AWS::LanguageExtensions at all:
```
Error: Resource with name [Transform] is invalid. Provided Transform ['AWS::LanguageExtensions', 'AWS::Serverless-2016-10-31'] is unsupported, use one of the following ['AWS::Serverless-2016-10-31']
Please follow the instructions in https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-publishing-applications.html
```
